### ISSUE TITLE
Print breakpoints

### ISSUE THREAD

**Issue by Valerz** [DeloitteDigitalAPAC/DDBreakpoints#18]
Hello,

I've set the defaults for the print break points to be:
$bp-print-min: 0 !default;
$bp-print-max: 1410 !default;

When i view in emulate the print rendering in chrome it looks fine. 
The debug breakpoints come up as xlarge. 

However when I ctrl + p on my chrome browser it looks funky and the debug breakpoints it comes up as xsmall. 

Am I missing something?

**Comment by dkeeghan** [comment]
Hi @Pizdetss.

When you print, the page will always display at xsmall because when printing the page size is around 550px. 

By setting the `$bp-print-max` variable you're telling the stylesheet to use all the styles up to `1410`px wide on that 550px wide page. 

Regarding print styles, I would recommend simplifying the print layout to just show content only - in most cases this means the 550px wide breakpoint works well for us. 

The advice in this article is really good: https://www.smashingmagazine.com/2011/11/how-to-set-up-a-print-style-sheet/ 

Hope that helps.

**Comment by Valerz** [comment]
Hi @dkeeghan 

Thanks for your quick reply. It makes sense. 
You can close this ticket. 

Cheers,
