### ISSUE TITLE
Using the largest breakpoint name in the max position returns 1emem

### ISSUE THREAD

**Issue by dkeeghan** [DeloitteDigitalAPAC/DDBreakpoints#7]
As @ryanmargheriti mentioned in his Pull Request #6 when you use the largest breakpoint name (e.g. `xxl`) as the max breakpoint:

```
@include bp(xl, xxl) {
    background:red;
}
```

the media query returned looks like:

```
@media only screen and (min-width: 77.75em) and (max-width: 1emem) {
  body {
    background: red; 
  }
}
```

**Comment by dkeeghan** [comment]
My recommendation for the solution is to throw a warning in the console and ignore the max-width at this point and just return:

```
@media only screen and (min-width: 77.75em) {
  body {
    background: red; 
  }
}
```

Thoughts @keeganstreet @hadimichael ?

**Comment by hdmchl** [comment]
Seems reasonable. I suppose we can infer what the user is trying to do and simply `@warn` them at compile time that we've made that assumption.

However before we make the assumption, we'll need to **confirm that they're referencing the largest available breakpoint**. This is to accommodate a use case where a user adds their own new breakpoint, in order to have something occur only between xl and xxl, for example.

In other words, if a developer needs a blue background that goes red between xl and xxl only, they add a breakpoint (e.g. `xxxl`) and use `xxl` as below.

``` sass
body {
  background: blue;
  @include bp(xl, xxl) {
      background: red;
  }
}
```

We can only apply our assumption if they've written `bp(xl, xxxl)`. So that

``` sass
.my-class {
  @include bp(xxl, xxxl) {
      margin: 20px;
  }
}
```

Can become:

``` sass
@media only screen and (min-width: <INSERT xxl-min-width>em) {
  .my-class {
    margin: 20px;
  }
}
```

Is that correct?

**Comment by dkeeghan** [comment]
Resolved a long time ago
